# Generated by Django 5.0.1 on 2026-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_description',
            field=models.CharField(blank=True, help_text="e.g., 'Starting from' or 'Per hour'", max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price in ZAR', max_digits=10, null=True),
        ),
    ]
