# Generated by Django 5.0.1 on 2026-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_service_price_description_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Event', help_text='e.g., Wedding, Music Video, Corporate Event', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Short description with icon'),
        ),
    ]
